{{- if and (not .Values.auth.existingSecret) .Values.auth.superuserPassword.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "htpg.fullname" . }}
  labels:
    {{- include "htpg.labels" . | nindent 4 }}
  annotations:
    # CRITICAL: Tells Helm/ArgoCD to never delete this secret
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
stringData:
  postgres-password: {{ .Values.auth.superuserPassword.value | quote }}
{{- end }}